version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  backend:
    image: nginx:1.20-alpine
    build:
      dockerfile: ./infra/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    ports:
      - "10082:80"

  web:
    build:
      context: ./web
    container_name: react_app
    volumes:
      - ./web:/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
