version: "3.9"
services:
  app:
    build: ./infra/php
    container_name: laravel_app
    volumes:
      - ./backend:/data
  
  back:
    image: nginx:1.20-alpine
    container_name: laravel_web
    volumes:
      - ./backend:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10082:80
    working_dir: /data

  web:
    build:
      context: ./web
    container_name: react_app
    volumes:
      - ./web:/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
