version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./front:/data

  web:
    image: nginx:1.20-alpine
    ports:
      - 10082:80
    volumes:
      - ./front:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data